language: android
env:
  global:
    - secure: VffBwEKi8v0WrJC2AFu8H5y9wl44ClJEsmMinQS5TSRTY+o0oeZ6erliGaWjmUqyU0DYUhkxHilyn41OeKTHI+wbBvdJx8vRCe/B+R5RFNDBkVClMViE8IjicMSwOyNQ4tW/rczSBB/iNAZ3xjBk+HZaf5xZkEqsmLgswwAWXmk=
    - secure: PsV548pDm8GL7Fv1uhlg8Oqyl+u6Kt6PwECWxoMiOh8VkJCd3KpAZDB3hIf3v+8JzG8G7co4Cg3Wggcu/q2L5CY3+DSkEnDEpFCfFG9+3NKEe336GGJrGTV7oNUmudrNPBGRUdkLafBvKNKcwOhCoSepFcjFLbdDLgMDbIxvaJU=
android:
  components:
  - platform-tools
  - tools
  - build-tools-21.1.1
  - android-21
sudo: false
cache:
  directories:
    - node_modules
    - www/lib
install:
- nvm install 5
- npm install
script:
- ionic platform add android
